/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ZustandImport } from './routes/zustand'
import { Route as ReduxImport } from './routes/redux'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ZustandRoute = ZustandImport.update({
  path: '/zustand',
  getParentRoute: () => rootRoute,
} as any)

const ReduxRoute = ReduxImport.update({
  path: '/redux',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/redux': {
      preLoaderRoute: typeof ReduxImport
      parentRoute: typeof rootRoute
    }
    '/zustand': {
      preLoaderRoute: typeof ZustandImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutRoute,
  ReduxRoute,
  ZustandRoute,
])

/* prettier-ignore-end */
